### ISSUE TITLE
No valid requirements.txt

### ISSUE THREAD

**Issue by pseudo-aloha** [ma3mool/goldeneye#14]
As stated in the title. After I clone the repo and I found that there is only requirements.txt under pytorchfi/. After I install the dependencies in requirements.txt and installed qtorch 0.3.0. The test program give me a huge number of Error messages. My environment is ubuntu 20.04 with a plane conda environment for this repo. The python version is 3.6. Thank you!

**Comment by ma3mool** [comment]
Hi @pseudo-aloha . It looks like you figured out the issue? Do you mind sharing here what was missing or needed, so that I can update the docs as well?

Thanks!
